.\" $NiH: ckmame.mdoc,v 1.8 2005/06/12 16:34:40 wiz Exp $
.\"
.\" Copyright (c) 2003, 2004, 2005 Thomas Klausner.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above
.\"    copyright notice, this list of conditions and the following
.\"    disclaimer in the documentation and/or other materials provided
.\"    with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THOMAS KLAUSNER ``AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd June 12, 2005
.Dt CKMAME 1
.Os
.Sh NAME
.Nm ckmame
.Nd verify MAME rom sets
.Sh SYNOPSIS
.Nm
.Op Fl bcdFfhKkLlnSsUuVvw
.Op Fl D Ar dbfile
.Op Ar game ...
.Sh DESCRIPTION
.Nm
is a program to check rom sets for MAME, the Multiple Arcade
Machine Emulator (see
.Lk http://www.mame.net/ ) .
(Actually, it supports more than that, you can also check sets for
e.g., Raine, Impact, or other emulators.)
It tells you which rom files are missing or have a wrong CRC, and can
delete unknown and unused files from the romsets (zipped only).
.Pp
MAME is an emulator for all kinds of historic and not so historic
arcade machines (video games, ranging from the 1970s to today).
Since MAME is emulating the games, it uses the original roms from the
arcade machines.
MAME's internal database contains extensive information on the roms,
including the sizes and CRCs (checksums) of the used roms.
Since some arcade games are variants of others and share some of the
same roms, there are also some internal dependencies of these so
called clones.
For space reasons the roms can be archived in zip files, and are
dynamically unzipped by MAME itself when you play a game.
.Nm
does not support rom sets not stored as zip files.
.Pp
.Nm
tries to create a
.Dq split romset
from your current collection.
This means that all files needed by the parent are kept in the
parent's zip file, and only the files needed by the clone (or child)
that are different from the parent's are kept in the child's zip.
For identifying the roms ckmame uses the sizes and CRCs; names are
only used for verification, since the MAME team likes to change rom's
names from version to version.
.Pp
.Nm
uses MAME's rom database, but it must be converted into a more
efficient format before the first use.
See
.Xr mkmamedb 1
for details.
.Pp
By default,
.Nm
will check the games named, or all games if none are given.
Shell wildcards are allowed.
If you want to trim the output to particular details, 
see the
.Sx OPTIONS
section below for details.
.Ss OPTIONS
Supported options:
.Bl -tag -width 22n
.It Fl b, -nobroken
Don't report unfixable errors.
See also
.Fl f
and
.Fl w .
.It Fl c , -correct
Report correct sets.
Normally they are not mentioned.
.It Fl D Ar dbfile , Fl -db Ar dbfile
Use
.Ar dbfile
as database file.
.It Fl d , -nonogooddumps
Don't report roms with no known good dumps.
.It Fl F , -fix
Fix rom sets; do as much as possible, such as renaming and moving
files.
.It Fl f , -nofixable
Don't report fixable errors.
See also
.Fl b
and
.Fl w .
.It Fl h , -help
Display a short help message.
.It Fl i , -integrity
Check integrity of zip archives and disk images
by computing checksums and comparing them with the
internally saved ones.
.It Fl K , -keep-unknown
Keep unknown files when fixing (default).
They are moved into a zip file with the same name under
.Pa roms/garbage .
See also
.Fl k .
.It Fl k , -delete-unknown
Don't keep unknown files when fixing.
See also
.Fl K .
.It Fl L , -keep-long
Keep too long files when fixing (default).
See also
.Fl K
and
.Fl l .
.It Fl l , -delete-long
Don't keep long files when fixing, delete them instead.
See also
.Fl L .
.It Fl n , -dryrun
Don't actually fix anything, just report what would be done.
.It Fl S , -samples
Check samples instead of roms.
.It Fl -superfluous
Only check for superfluous files in rom sets.
.It Fl s , -nosuperfluous
Don't report superfluous (unneeded) files.
.It Fl U , -keep-unused
Keep unused files when fixing.
Unused files are files that should, and do exist in other places.
See also
.Fl u .
.It Fl u , -delete-unused
Don't keep unused files when fixing (default), delete them instead.
See also
.Fl U .
.It Fl V , -version
Display program name and version number.
.It Fl v , -verbose
Print fixes made.
.It Fl w , -nowarnings
Print only unfixable error, like missing or completely incorrect roms.
See also
.Fl b
and
.Fl f .
.It Fl X , -ignoreextra
Do not mention extra files that are in the roms or samples dirs
respectively.
Most of the time these are romsets whose names have changed.
Additionally,
.Nm
creates a
.Pa roms/garbage
directory (see also
.Fl K ) ,
which you will also be warned about.
.El
.Sh ENVIRONMENT
.Bl -tag -width 10n
.It Ev MAMEDB
Location for the database file.
Can be overridden with the
.Fl D
option.
Defaults to
.Dq Pa mame.db .
.It Ev ROMPATH
Location for the rom zip files.
Defaults to
.Dq Pa \&. .
.El
.Sh EXAMPLES
Print a report about the current state of your rom sets in the
.Pa roms
subdir of the current dir:
.Dl Ic ckmame
.Pp
Fix all sets and only report unfixable errors, omitting those
roms where no good dump exists:
.Dl Ic ckmame -Fwd
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Dieter Baron
.Aq dillo@giga.or.at
and
.An Thomas Klausner
.Aq tk@giga.or.at .
.Sh BUGS
Files that are in clone sets of a set, but would belong in the parent
set, are not moved automatically.
Add them to the parent set manually, then run
.Ic ckmame -F
to remove them from the clone set(s) automatically.
