.\" Copyright (c) 2003-2022 Dieter Baron and Thomas Klausner.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above
.\"    copyright notice, this list of conditions and the following
.\"    disclaimer in the documentation and/or other materials provided
.\"    with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THOMAS KLAUSNER ``AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd January 28, 2022
.Dt CKMAME 1
.Os
.Sh NAME
.Nm ckmame
.Nd verify MAME ROM sets
.Sh SYNOPSIS
.Nm
.Op Fl CcFhjuVv
.Op Fl D Ar dbfile
.Op Fl e Ar dir
.Op Fl O Ar dbfile
.Op Fl R Ar dir
.Op Fl T Ar file
.Op Fl Fl complete-games-only
.Op Fl Fl config Ar file
.Op Fl Fl copy-from-extra
.Op Fl Fl create-fixdat
.Op Fl Fl extra-directory Ar dir
.Op Fl Fl fix
.Op Fl Fl fixdat-directory Ar dir
.Op Fl Fl game-list Ar file
.Op Fl Fl help
.Op Fl Fl keep-old-duplicate
.Op Fl Fl move-from-extra
.Op Fl Fl no-complete-games-only
.Op Fl Fl no-create-fixdat
.Op Fl Fl no-report-correct
.Op Fl Fl no-report-detailed
.Op Fl Fl no-report-fixable
.Op Fl Fl no-report-missing
.Op Fl Fl no-report-summary
.Op Fl Fl old-db Ar dbfile
.Op Fl Fl report-correct
.Op Fl Fl report-detailed
.Op Fl Fl report-fixable
.Op Fl Fl report-missing
.Op Fl Fl report-summary
.Op Fl Fl rom-db Ar dbfile
.Op Fl Fl rom-directory Ar dir
.Op Fl Fl roms-unzipped
.Op Fl Fl set Ar name
.Op Fl Fl verbose
.Op Fl Fl version
.Op Ar game ...
.Sh DESCRIPTION
.Nm
is a program to check ROM sets for MAME, the Multiple Arcade
Machine Emulator (see
.Pa https://www.mamedev.org/ ) ,
or other emulators that provide ROM set information in a compatible
way.
This is the same format as clrmamepro dat files.
.Nm
tells you which ROM files are missing or have a wrong checksum,
can delete unknown and unused files from the ROM sets, and rename
or move files.
.Pp
MAME is an emulator for numerous arcade machines (video games, ranging
from the 1970s to today).
Since MAME is emulating the games, it uses the original images from
the arcade machines' original ROM chips.
MAME's internal database contains extensive information on the
ROMs, including the sizes and checksums of the used ROMs.
Since some arcade games are variants of others and share some of the
same ROMs, there are also internal dependencies between these so
called clones.
To save space, ROMs can be archived in zip files and
dynamically unzipped by MAME when you play a game.
.Nm
does only support ROM sets stored as zip files or unpacked,
collected in directories per game.
.Pp
.Nm
tries to create a
.Dq split ROM set
from your current collection.
This means that all files needed by the parent are kept in the
parent's zip file, and only the files needed by the clone (or child)
that are different from the parent's are kept in the child's zip file.
For identifying the ROMs ckmame uses the sizes and checksums; names are
only used for verification, since the MAME team often renames ROMs.
.Pp
While
.Nm
uses MAME's ROM database, it must be converted into a more
efficient format before use.
See
.Xr mkmamedb 1
for details.
.Pp
By default,
.Nm
will check the games named on the command line, or all games if none
are given.
Shell wildcards are allowed.
You can use command line options to select which type of errors to report.
.Ss OPTIONS
Supported options:
.Bl -tag -width 22n
.It Fl C , Fl Fl complete-games-only
Only create complete games.
ROMs for incomplete games are moved to the
.Pa needed
directory.
.It Fl c , Fl Fl report-correct
Report status of ROMs that are correct.
By default they are not mentioned.
.It Fl Fl config Ar file
read configuration from
.Ar file .
See the
.Sx CONFIG FILE
section for more details.
.It Fl Fl copy-from-extra
Keep used files in extra directories (default).
.It Fl Fl create-fixdat
Create a clrmamepro-style
.Dq fixdat
file, i.e. an XML file containing only the files missing in the ROM
set compared to the database used.
.It Fl D , Fl Fl rom-db Ar dbfile
Use
.Ar dbfile
instead of the default
.Pa mame.db
as the database.
.It Fl e , Fl Fl extra-directory Ar dir
Search for missing files in directory dir (multiple directories can be
specified by repeating this option).
.It Fl F , Fl Fl fix
Fix the ROM set.
By default, only the status is reported.
.It Fl Fl fixdat-directory Ar dir
Create the fixdat (see
.Fl Fl create-fixdat )
in
.Ar dir
instead of the current directory.
.It Fl h , Fl Fl help
Display a short usage.
.It Fl j , Fl Fl move-from-extra
Remove used files from extra directories.
Opposite of
.Fl Fl copy-from-extra .
.It Fl Fl keep-old-duplicate
Keep files in ROM set that are also in old ROM database.
.It Fl Fl no-complete-games-only
Keep partial games in ROM set (default).
.It Fl Fl no-create-fixdat
Do not create a fixdat for the missing ROM sets (default).
.It Fl Fl no-report-correct
Don't report status of ROMs that are correct (default).
.It Fl Fl no-report-detailed
Don't report status of every ROM (default).
.It Fl Fl no-report-fixable
Don't report status of ROMs that can be fixed.
.It Fl Fl no-report-missing
Don't report status of ROMs that are missing.
.It Fl Fl no-report-summary
Don't print summary of ROM set status (default).
.It Fl O , Fl Fl old-db Ar dbfile
Assume that the files in the database
.Ar dbfile
exist in some other location (e.g., on an offline disk or backup
medium).
.It Fl R , Fl Fl rom-directory Ar dir
Look for the ROM set in the directory
.Ar dir
instead of the default
.Pa roms .
.It Fl Fl report-detailed
Report status of every ROM that is checked.
.It Fl Fl report-fixable
Report status of ROMs that can be fixed (default).
.It Fl Fl report-missing
Report status of ROMs that are missing (default).
.It Fl Fl report-summary
Print summary of ROM set status at the end of the output.
.It Fl Fl set Ar name
Check ROM set name.
This uses the configuration from the corresponding section in the
Config files.
See
.Sx CONFIG FILES
for details
.It Fl T , Fl Fl game-list Ar file
Read the list of games to check from
.Ar file .
.Ar file
should contain one line per game.
.It Fl u , Fl Fl roms-unzipped
Instead of looking for ROMs in the ZIP archive
.Pa roms/games.zip ,
look for them in the directory
.Pa roms/games/
in the file system.
.It Fl V , Fl Fl version
Display version number.
.It Fl v , Fl Fl verbose
Print fixes made.
.El
.Sh ENVIRONMENT
.Bl -tag -width 10n
.It Ev MAMEDB
Location for the database file.
Can be overridden with the
.Fl Fl dbfile
option.
Defaults to
.Dq Pa mame.db .
.It Ev MAMEDB_OLD
Location for the database file of files that exist elsewhere.
Can be overridden with the
.Fl Fl old-db
option.
Defaults to
.Dq Pa old.db .
.El
.Sh FILES
By default, the configuration is read from
.Pa ~/.config/ckmame/ckmamerc
and
.Pa .ckmamerc
if they exist, in this order.
.Pp
The database file to read from defaults to
.Pa mame.db
and the roms are expected in the
.Pa roms
directory.
.Pp
Unknown files are moved to the sub-directory
.Pa unknown .
Files that will be needed by other games in the ROM set are moved
to the
.Pa needed
directory.
.Pp
.Nm
creates
.Pa .ckmame.db
files in the rom directory as well as the directories given with
.Fl e .
These files are databases containing file names, sizes, and their
hashes.
The database information used when the file hasn't changed
since the last run (i.e. same size and modification time).
.Sh EXAMPLES
Print a report about the current state of your ROM sets in the
.Pa roms
subdirectory of the current dir:
.Dl Ic ckmame
.Pp
Fix all sets and only report unfixable errors, omitting those
ROMs where no good dump exists:
.Dl Ic ckmame -Fd
.Pp
Fix all sets using the files found in
.Ar updatedir ,
removing files from there that are copied to the ROM set:
.Dl Ic ckmame -Fj -e updatedir
.Ss CONFIG FILE
By default,
.Nm
reads the config files
.Pa ~/.config/ckmame/ckmamerc
and
.Pa .ckmamerc
and the one given by the
.Fl Fl config
option, in this order.
The files are in TOML format.
The
.Dq [global]
section contains defaults for all sets, while the
.Dq ["SET NAME"]
option adds overrides for the
.Dl Dq SET NAME
set (as provided by the
.Fl Fl set
option).
The options are set using the long name options from above.
Most options are boolean options, so the "no-" options are set by
setting the corresponding option to false, i.e.
.Fl Fl no-report-missing
is written as
.Dl report-missing = false
in the config file.
.Fl Fl copy-from-extra
is set by
.Dl move-from-extra = false
The following options can not be set from the config file:
.Bl -item -offset indent -compact
.It
.Fl Fl config
.It
.Fl Fl fix
.It
.Fl Fl help
.It
.Fl Fl version
.El
.Pp
The
.Cm extra-directory
config parameter overrides the search directories, and there is
.Cm extra-directory-append
if you want add to the search path instead.
.Pp
For example:
.Bd -literal
[global]
verbose = true

["Big Set"]
verbose = false
rom-dir = "Big Set ROMs"
dbfile = "Big Set.db"

["Unzipped Set"]
roms-unzipped = true
rom-dir = "Unzipped Set ROMs"
dbfile = "Unzipped Set.db"
.Ed
.Pp
This configuration would by default report verbosely,
but override this for the "Big Set" set.
It would also set the rom directories and database files
for both the "Big Set" and the "Unzipped Set" and not use
ZIP archives for the latter.
.Pp
Example run:
.Dl ckmame --set "Big Set"
.Sh DIAGNOSTICS
Most messages should be straightforward.
Two need special explanations:
.Pp
If a file is marked as
.Dq broken ,
it means that the computed checksum is not the same
as the checksum stored in the zip archive,
usually because there has been a decompression error.
.Pp
If a ROM or disk is marked with
.Dq checksum mismatch ,
the primary checksum matches, but one of the other checksums
does not.
The primary checksum for ROMs is CRC32, for disks MD5.
.Sh SEE ALSO
.Xr dumpgame 1 ,
.Xr mkmamedb 1
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Dieter Baron Aq Mt dillo@nih.at
and
.An Thomas Klausner Aq Mt tk@giga.or.at .
