.\" $NiH: ckmame.mdoc,v 1.3 2005/12/23 09:00:51 wiz Exp $
.\"
.\" Copyright (c) 2003, 2004, 2005 Dieter Baron and Thomas Klausner.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above
.\"    copyright notice, this list of conditions and the following
.\"    disclaimer in the documentation and/or other materials provided
.\"    with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THOMAS KLAUSNER ``AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd December 22, 2005
.Dt CKMAME 1
.Os
.Sh NAME
.Nm ckmame
.Nd verify MAME ROM sets
.Sh SYNOPSIS
.Nm
.Op Fl bcdFfhjKkLlnSsVvw
.Op Fl D Ar dbfile
.Op Fl e Ar dir
.Op Ar game ...
.Sh DESCRIPTION
.Nm
is a program to check ROM sets for MAME, the Multiple Arcade
Machine Emulator (see
.Pa http://www.mame.net/ ) ,
or other emulators that provide ROM set information in a compatible
way (e.g., Raine, Impact, or other emulators.)
It tells you which ROM files are missing or have a wrong checksum,
can delete unknown and unused files from the ROM sets, and rename
or move files.
.Pp
MAME is an emulator for numerous arcade machines (video games, ranging
from the 1970s to today).
Since MAME is emulating the games, it uses the original images from
the arcade machines' original ROM chips.  MAME's internal database
contains extensive information on the ROMs, including the sizes
and checksums of the used ROMs.
Since some arcade games are variants of others and share some of the
same ROMs, there are also internal dependencies between these so
called clones.
To save space, ROMs can be archived in zip files and
dynamically unzipped by MAME when you play a game.
.Nm
does only support ROM sets stored as zip files.
.Pp
.Nm
tries to create a
.Dq split ROM set
from your current collection.
This means that all files needed by the parent are kept in the
parent's zip file, and only the files needed by the clone (or child)
that are different from the parent's are kept in the child's zip file.
For identifying the ROMs ckmame uses the sizes and checksums; names are
only used for verification, since the MAME team often renames ROMs.
.Pp
While
.Nm
uses MAME's ROM database, it must be converted into a more
efficient format before use.
See
.Xr mkmamedb 1
for details.
.Pp
By default,
.Nm
will check the games named on the command line, or all games if none
are given.
Shell wildcards are allowed.
You can use command line options to select which type of errors to report.
.Ss OPTIONS
Supported options:
.Bl -tag -width 22n
.It Fl b, -nobroken
Don't report unfixable errors.
See also
.Fl f
and
.Fl w .
.It Fl c , -correct
Report correct sets.
Normally they are not mentioned.
.It Fl D Ar dbfile , Fl -db Ar dbfile
Use
.Ar dbfile
as database file.
.It Fl d , -nonogooddumps
Don't report ROMs with no known good dumps.
.It Fl e , -search Ar dir
Look for missing files in directory
.Ar dir
and its subdirectories.
Recommended for use with update sets.
See also
.Fl j .
.It Fl F , -fix
Fix ROM sets; do as much as possible, such as renaming and moving
files.
.It Fl f , -nofixable
Don't report fixable errors.
See also
.Fl b
and
.Fl w .
.It Fl h , -help
Display a short help message.
.It Fl i , -integrity
Check integrity of zip archives and disk images
by computing checksums and comparing them with the
internally saved ones.
.It Fl j , -delete-found
When using
.Fl e ,
delete files that are copied to the ROM set.
See also
.Fl -keep-found .
.It Fl -keep-found
When using
.Fl e ,
do not remove files that are copied to the ROM set (default).
See also
.Fl j .
.It Fl K , -keep-unknown
Keep unknown files when fixing (default).
They are moved into a zip file with the same name under
.Pa roms/garbage .
See also
.Fl k .
.It Fl k , -delete-unknown
Don't keep unknown files when fixing.
See also
.Fl K .
.It Fl L , -keep-long
Keep too long files when fixing (default).
See also
.Fl K
and
.Fl l .
.It Fl l , -delete-long
Don't keep long files when fixing, delete them instead.
See also
.Fl L .
.It Fl n , -dryrun
Don't actually fix anything, just report what would be done.
.It Fl S , -samples
Check samples instead of ROMs.
.It Fl -superfluous
Only check for superfluous files in ROM sets.
.It Fl s , -nosuperfluous
Don't report superfluous (unneeded) files.
.It Fl V , -version
Display program name and version number.
.It Fl v , -verbose
Print fixes made.
.It Fl w , -nowarnings
Print only unfixable error, like missing or completely incorrect ROMs.
See also
.Fl b
and
.Fl f .
.It Fl X , -ignoreextra
Do not mention extra files that are in the ROMs or samples dirs
respectively.
Most of the time these are ROM sets whose names have changed.
Additionally,
.Nm
creates a
.Pa roms/garbage
directory (see also
.Fl K ) ,
which you will also be warned about.
.El
.Sh ENVIRONMENT
.Bl -tag -width 10n
.It Ev MAMEDB
Location for the database file.
Can be overridden with the
.Fl D
option.
Defaults to
.Dq Pa mame.db .
.It Ev ROMPATH
Location for the ROM zip files.
Defaults to
.Dq Pa \&. .
.El
.Sh EXAMPLES
Print a report about the current state of your ROM sets in the
.Pa roms
subdir of the current dir:
.Dl Ic ckmame
.Pp
Fix all sets and only report unfixable errors, omitting those
ROMs where no good dump exists:
.Dl Ic ckmame -Fwd
.Sh DIAGNOSTICS
Most messages should be straightforward.
Two need special explanations:
.Pp
If a file is marked as
.Dq broken ,
it means that the computed checksum is not the same
as the checksum stored in the zip archive,
usually because there has been a decompression error.
.Pp
If a ROM or disk is marked with
.Dq checksum mismatch ,
the primary checksum matches, but one of the other checksums
does not.
The primary checksum for ROMs is CRC32, for disks MD5.
.Sh SEE ALSO
.Xr dumpgame 1 ,
.Xr mkmamedb 1 ,
.Xr xmame 6
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Dieter Baron
.Aq dillo@giga.or.at
and
.An Thomas Klausner
.Aq tk@giga.or.at .
