.\" Copyright (c) 2024 Dieter Baron and Thomas Klausner.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above
.\"    copyright notice, this list of conditions and the following
.\"    disclaimer in the documentation and/or other materials provided
.\"    with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THOMAS KLAUSNER ``AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd November 4, 2024
.Dt CKSTATUS 1
.Os
.Sh NAME
.Nm ckstatus
.Nd report on
.Xr ckmame 1
runs
.Sh SYNOPSIS
.Nm
.Op Fl Fl all-missing
.Op Fl Fl all-sets
.Op Fl Fl changes
.Op Fl Fl config Ar file
.Op Fl Fl correct
.Op Fl Fl correct-mia
.Op Fl h , Fl Fl help
.Op Fl Fl list-sets
.Op Fl Fl missing
.Op Fl Fl runs
.Op Fl Fl set Ar pattern
.Op Fl Fl status-db Ar dbfile
.Op Fl V , Fl Fl version
.Sh DESCRIPTION
.Nm
is a program to report on the results and/or changes of
.Xr ckmame 1
runs on a ROM set.
The data is read from the
.Pa .ckmame-status.db
file in the current directory, or the place configured in the config
file, either for the default or the selected set(s).
It compares the output of different runs, i.e. starts of
.Xr ckmame 1.
.Ss OPTIONS
Supported options:
.Bl -tag -width 20n
.It Fl Fl all-missing
List all missing ROMs.
.It Fl Fl all-sets
Report on all configured sets.
.It Fl Fl changes
List the changes in between two runs.
By default, the newest two runs are compared.
.It Fl Fl config Ar file
Read the configuration from
.Ar file .
.It Fl Fl correct
List all correct ROMs.
.It Fl Fl correct-mia
List all correct ROMs that are MIA according to the database.
.It Fl h , Fl Fl help
Show a short help.
.It Fl Fl list-sets
List all configured sets, for the
.Fl Fl set
option.
.It Fl Fl missing
List all missing ROMs except those that are MIA according to the
database.
.It Fl Fl runs
List all available runs.
.It Fl Fl set Ar pattern
Report on all sets matching
.Ar pattern .
.It Fl Fl status-db Ar dbfile
Use
.Ar dbfile
instead of the default
.Pa .ckmame-status.db .
.It Fl V , Fl Fl version
Report the version of
.Nm .
.El
.Sh FILES
By default, the run information is read from
.Pa .ckmame-status.db .
.Sh SEE ALSO
.Xr ckmame 1
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Dieter Baron Aq Mt dillo@nih.at
and
.An Thomas Klausner Aq Mt wiz@gatalith.at .
