.\" Copyright (c) 2005-2022 Dieter Baron and Thomas Klausner.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above
.\"    copyright notice, this list of conditions and the following
.\"    disclaimer in the documentation and/or other materials provided
.\"    with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior
.\"    written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THOMAS KLAUSNER ``AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd January 28, 2022
.Dt MKMAMEDB 1
.Os
.Sh NAME
.Nm mkmamedb
.Nd create database for use by ckmame
.Sh SYNOPSIS
.Nm
.Op Fl htuV
.Op Fl C Ar types
.Op Fl F Ar format
.Op Fl o Ar dbfile
.Op Fl x Ar pattern
.Op Fl Fl detector Ar xml\-file
.Op Fl Fl directory\-cache
.Op Fl Fl exclude Ar pattern
.Op Fl Fl format Ar format
.Op Fl Fl hash\-types Ar types
.Op Fl Fl help
.Op Fl Fl no\-directory\-cache
.Op Fl Fl only\-files Ar pattern
.Op Fl Fl output Ar dbfile
.Op Fl Fl prog\-description Ar description
.Op Fl Fl prog\-name Ar name
.Op Fl Fl prog\-version Ar version
.Op Fl Fl roms\-unzipped
.Op Fl Fl skip\-files Ar pattern
.Op Fl Fl use\-temp\-directory
.Op Fl Fl version
.Op Ar rominfo\-file ...
.Sh DESCRIPTION
.Nm
converts ROM set descriptions from one format to another.
.Pp
The ROM set description is read from the specified files (or
directories) or the standard input if no files are specified.
The default output file is
.Pa mame.db .
You can override it with the
.Fl o
option or the
.Ev MAMEDB
environment variable.
.Pp
Supported input formats are:
.Bl -bullet -offset indent -compact
.It
CMPro dat file
.It
MAME XML file
.It
MESS Softlist XML file
.It
Romcenter dat file
.It
.Xr ckmame 1
database format
.It
directory of zip archives
.It
directory with subdirectories (with
.Fl u ) ;
each sub-directory is taken as a game
.El
Supported output formats are:
.Bl -bullet -offset indent -compact
.It
.Xr ckmame 1
database format
.It
CMPro dat file
.It
Logiqx XML dat file
.It
.Xr mtree 8
file
.El
.Pp
The CMPro file format is described at
.Pa http://www.logiqx.com/FAQs/CMPro.shtml ,
the DTD for MAME xml can be found in
.Pa PREFIX/share/doc/ckmame/ .
.Ss OPTIONS
.Nm
supports the following options:
.Bl -tag -width XCXtypesXXXhashXtypesXtypesXX
.It Fl C Ar types , Fl Fl hash\-types Ar types
A comma separated list of hash types to compute when creating a ROM
set description from a directory of zip archives.
Supported hash types are: crc, md5, sha1.
Default are all.
.It Fl Fl detector Ar xml\-file
Use CMPro XML header skip detector description from
.Ar file .
This overrides any detectors given in the file itself.
.Nm
looks for the detector in the input file (if it is a zip file) or
the directory of the input file.
.It Fl Fl directory\-cache
When
.Nm
is used to create a database from an input directory, it will by
default write a
.Pa .ckmame.db
database file to it, caching the directory contents' hashes in it so
that consecutive re-runs are faster.
When
.Nm
finds such a database, it only computes the hashes for the files that
have changed since the last run.
.It Fl F Ar format , Fl Fl format Ar format
Specify output format.
Supported formats are 
.Cm cm 
(clrmamepro dat file),
.Cm dat
(XML datfile),
.Cm db
.Xr ( ckmame 1
database), and
.Cm mtree
.Xr ( mtree 8
file).
The default is cm.
.It Fl h , Fl Fl help
Display a short help message.
.It Fl Fl no\-directory\-cache
Turn off
.Fl Fl directory\-cache .
.It Fl o Ar dbfile , Fl Fl output Ar dbfile
Write to database
.Ar dbfile
instead of the default
.Dq Pa mame.db .
.It Fl Fl only\-files Ar pattern
When reading files from the file system as input,
only accept files matching the shell glob
.Ar pattern .
.It Fl Fl prog\-description Ar description
Set description for the program the ROM info is from.
.It Fl Fl prog\-name Ar name
Set name of the program the ROM info is from.
.It Fl Fl prog\-version Ar version
Set version of the program the ROM info is from.
.It Fl Fl skip\-files Ar pattern
When reading files from the file system as input,
skip files matching the shell glob
.It Fl t , Fl Fl use\-temp\-directory
Create the output in a temporary directory and move it to the real
output when finished.
This might speed up the creation e.g. of
.Pa mame.db
when your current working directory is on a slow file system.
.It Fl u , Fl Fl roms\-unzipped
ROMs are files on the disk.
Each game is represented by a directory instead of a ZIP archive.
Only relevant when creating a database based on file system contents.
.It Fl V , Fl Fl version
Display program name and version number.
.It Fl x Ar pat , Fl Fl exclude Ar pat
Exclude games with names matching
.Ar pat
from the created database.
.El
.Sh ENVIRONMENT
.Bl -tag -width 10n
.It Ev MAMEDB
Location for the database file.
Can be overridden with the
.Fl o
option.
Defaults to
.Dq Pa mame.db .
.El
.Sh EXAMPLES
Get an input file for
.Xr mkmamedb 1
from MAME and convert it to the internal database format:
.Bd -literal
# mame \-listxml | mkmamedb
.Ed
.Sh SEE ALSO
.Xr ckmame 1 ,
.Xr dumpgame 1
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Dieter Baron Aq dillo@nih.at
and
.An Thomas Klausner Aq Mt tk@giga.or.at .
